spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: hamza.elaafani.2001@gmail.com
    password: elpbiehtvoncbyjd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
